/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_defcontainer_MeasurementUtils */

#ifndef _Included_com_android_defcontainer_MeasurementUtils
#define _Included_com_android_defcontainer_MeasurementUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_defcontainer_MeasurementUtils
 * Method:    native_measureDirectory
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_android_defcontainer_MeasurementUtils_native_1measureDirectory
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
